// AUTO-GENERATED by scripts/build-media.mjs — do not edit by hand.
export const mediaManifest = {
  "artist-ashley-gall": {
    "w": 960,
    "h": 640,
    "widths": [
      640,
      960
    ],
    "color": "#787878",
    "alpha": false
  },
  "artist-chantel-red": {
    "w": 1320,
    "h": 1125,
    "widths": [
      640,
      1280,
      1320
    ],
    "color": "#e8e8e8",
    "alpha": false
  },
  "artist-chantel": {
    "w": 2500,
    "h": 1568,
    "widths": [
      640,
      1280,
      1920,
      2500
    ],
    "color": "#081808",
    "alpha": false
  },
  "artist-chiggz": {
    "w": 2500,
    "h": 1667,
    "widths": [
      640,
      1280,
      1920,
      2500
    ],
    "color": "#181818",
    "alpha": false
  },
  "artist-ecosystem": {
    "w": 566,
    "h": 356,
    "widths": [
      566
    ],
    "color": "#080808",
    "alpha": false
  },
  "artist-jarryd-james": {
    "w": 640,
    "h": 426,
    "widths": [
      640
    ],
    "color": "#080808",
    "alpha": false
  },
  "artist-kily-safari": {
    "w": 2500,
    "h": 1666,
    "widths": [
      640,
      1280,
      1920,
      2500
    ],
    "color": "#081818",
    "alpha": false
  },
  "artist-legend": {
    "w": 858,
    "h": 604,
    "widths": [
      640,
      858
    ],
    "color": "#080808",
    "alpha": false
  },
  "artist-lil-pump": {
    "w": 1012,
    "h": 675,
    "widths": [
      640,
      1012
    ],
    "color": "#080808",
    "alpha": false
  },
  "artist-lowkey": {
    "w": 1015,
    "h": 676,
    "widths": [
      640,
      1015
    ],
    "color": "#282828",
    "alpha": false
  },
  "artist-mike-snell": {
    "w": 1463,
    "h": 975,
    "widths": [
      640,
      1280,
      1463
    ],
    "color": "#080808",
    "alpha": false
  },
  "artist-mikey-dam": {
    "w": 864,
    "h": 582,
    "widths": [
      640,
      864
    ],
    "color": "#283838",
    "alpha": false
  },
  "artist-nle-choppa": {
    "w": 864,
    "h": 576,
    "widths": [
      640,
      864
    ],
    "color": "#d8b898",
    "alpha": false
  },
  "artist-ribby247": {
    "w": 2500,
    "h": 1666,
    "widths": [
      640,
      1280,
      1920,
      2500
    ],
    "color": "#98a8a8",
    "alpha": false
  },
  "artist-yxng-ciiber": {
    "w": 2024,
    "h": 1398,
    "widths": [
      640,
      1280,
      1920,
      2024
    ],
    "color": "#080808",
    "alpha": false
  },
  "artist-ziezie": {
    "w": 625,
    "h": 416,
    "widths": [
      625
    ],
    "color": "#080808",
    "alpha": false
  },
  "award-badc": {
    "w": 225,
    "h": 225,
    "widths": [
      225
    ],
    "color": "#988858",
    "alpha": true
  },
  "award-muse": {
    "w": 1836,
    "h": 686,
    "widths": [
      640,
      1280,
      1836
    ],
    "color": "#080808",
    "alpha": true
  },
  "badge-come-again": {
    "w": 2476,
    "h": 577,
    "widths": [
      640,
      1280,
      1920,
      2476
    ],
    "color": "#080808",
    "alpha": true
  },
  "chantel-polaroid": {
    "w": 2500,
    "h": 3333,
    "widths": [
      640,
      1280,
      1920,
      2500
    ],
    "color": "#080808",
    "alpha": false
  },
  "cover-hoedown": {
    "w": 2500,
    "h": 2500,
    "widths": [
      640,
      1280,
      1920,
      2500
    ],
    "color": "#281818",
    "alpha": false
  },
  "cover-my-hometown": {
    "w": 2500,
    "h": 2500,
    "widths": [
      640,
      1280,
      1920,
      2500
    ],
    "color": "#b8c8d8",
    "alpha": false
  },
  "cover-not-fair": {
    "w": 2500,
    "h": 2500,
    "widths": [
      640,
      1280,
      1920,
      2500
    ],
    "color": "#181818",
    "alpha": false
  },
  "cover-paperweight": {
    "w": 2500,
    "h": 2500,
    "widths": [
      640,
      1280,
      1920,
      2500
    ],
    "color": "#181818",
    "alpha": false
  },
  "logo-globe-black": {
    "w": 2500,
    "h": 2500,
    "widths": [
      640,
      1280,
      1920,
      2500
    ],
    "color": "#080808",
    "alpha": true
  },
  "logo-globe-white": {
    "w": 2500,
    "h": 2500,
    "widths": [
      640,
      1280,
      1920,
      2500
    ],
    "color": "#080808",
    "alpha": true
  },
  "mezmure-hat": {
    "w": 2016,
    "h": 3024,
    "widths": [
      640,
      1280,
      1920,
      2016
    ],
    "color": "#181818",
    "alpha": false
  },
  "mezmure-silhouette": {
    "w": 1022,
    "h": 1725,
    "widths": [
      640,
      1022
    ],
    "color": "#080808",
    "alpha": false
  },
  "mike-snell-jersey": {
    "w": 1170,
    "h": 1192,
    "widths": [
      640,
      1170
    ],
    "color": "#d8d8e8",
    "alpha": false
  },
  "mood-blue": {
    "w": 842,
    "h": 561,
    "widths": [
      640,
      842
    ],
    "color": "#080808",
    "alpha": false
  },
  "rob-rivers-studio": {
    "w": 2500,
    "h": 3333,
    "widths": [
      640,
      1280,
      1920,
      2500
    ],
    "color": "#080808",
    "alpha": false
  },
  "studio-control-room": {
    "w": 2390,
    "h": 1593,
    "widths": [
      640,
      1280,
      1920,
      2390
    ],
    "color": "#080808",
    "alpha": false
  },
  "studio-montage": {
    "w": 2214,
    "h": 1565,
    "widths": [
      640,
      1280,
      1920,
      2214
    ],
    "color": "#282828",
    "alpha": false
  },
  "team-jarryd-james": {
    "w": 750,
    "h": 879,
    "widths": [
      640,
      750
    ],
    "color": "#d8d8c8",
    "alpha": false
  },
  "team-mezmure": {
    "w": 1440,
    "h": 1779,
    "widths": [
      640,
      1280,
      1440
    ],
    "color": "#080808",
    "alpha": false
  },
  "team-mike-snell": {
    "w": 1463,
    "h": 1898,
    "widths": [
      640,
      1280,
      1463
    ],
    "color": "#080808",
    "alpha": false
  },
  "team-mikey-dam": {
    "w": 542,
    "h": 732,
    "widths": [
      542
    ],
    "color": "#080808",
    "alpha": false
  },
  "team-rob-rivers": {
    "w": 943,
    "h": 1342,
    "widths": [
      640,
      943
    ],
    "color": "#181818",
    "alpha": false
  },
  "whitewall-logo": {
    "w": 2500,
    "h": 833,
    "widths": [
      640,
      1280,
      1920,
      2500
    ],
    "color": "#080808",
    "alpha": true
  },
  "work-bush-tucker": {
    "w": 1912,
    "h": 1074,
    "widths": [
      640,
      1280,
      1912
    ],
    "color": "#e8e8e8",
    "alpha": false
  },
  "work-chef": {
    "w": 1704,
    "h": 1136,
    "widths": [
      640,
      1280,
      1704
    ],
    "color": "#080808",
    "alpha": false
  },
  "work-coopers": {
    "w": 2101,
    "h": 1401,
    "widths": [
      640,
      1280,
      1920,
      2101
    ],
    "color": "#78b878",
    "alpha": false
  },
  "work-editorial": {
    "w": 2101,
    "h": 1401,
    "widths": [
      640,
      1280,
      1920,
      2101
    ],
    "color": "#080808",
    "alpha": false
  },
  "work-jaguar": {
    "w": 2314,
    "h": 1248,
    "widths": [
      640,
      1280,
      1920,
      2314
    ],
    "color": "#080818",
    "alpha": false
  },
  "work-maritimo": {
    "w": 2500,
    "h": 1401,
    "widths": [
      640,
      1280,
      1920,
      2500
    ],
    "color": "#587898",
    "alpha": false
  },
  "work-painter": {
    "w": 1881,
    "h": 1254,
    "widths": [
      640,
      1280,
      1881
    ],
    "color": "#f8f8e8",
    "alpha": false
  },
  "work-pivotel": {
    "w": 2500,
    "h": 1444,
    "widths": [
      640,
      1280,
      1920,
      2500
    ],
    "color": "#480808",
    "alpha": false
  },
  "work-pour": {
    "w": 2376,
    "h": 1190,
    "widths": [
      640,
      1280,
      1920,
      2376
    ],
    "color": "#282828",
    "alpha": false
  },
  "work-sequins": {
    "w": 2500,
    "h": 1139,
    "widths": [
      640,
      1280,
      1920,
      2500
    ],
    "color": "#382828",
    "alpha": false
  },
  "work-superboost": {
    "w": 2097,
    "h": 1398,
    "widths": [
      640,
      1280,
      1920,
      2097
    ],
    "color": "#080818",
    "alpha": false
  },
  "work-teal": {
    "w": 2500,
    "h": 1152,
    "widths": [
      640,
      1280,
      1920,
      2500
    ],
    "color": "#080808",
    "alpha": false
  },
  "ww-armchair": {
    "w": 2268,
    "h": 2967,
    "widths": [
      640,
      1280,
      1920,
      2268
    ],
    "color": "#c8c8b8",
    "alpha": false
  },
  "ww-ball-chair": {
    "w": 584,
    "h": 1040,
    "widths": [
      584
    ],
    "color": "#585848",
    "alpha": false
  },
  "ww-cap": {
    "w": 2500,
    "h": 3750,
    "widths": [
      640,
      1280,
      1920,
      2500
    ],
    "color": "#f8f8f8",
    "alpha": false
  },
  "ww-denim": {
    "w": 2240,
    "h": 3360,
    "widths": [
      640,
      1280,
      1920,
      2240
    ],
    "color": "#e8e8f8",
    "alpha": false
  },
  "ww-phone": {
    "w": 2142,
    "h": 2856,
    "widths": [
      640,
      1280,
      1920,
      2142
    ],
    "color": "#c8d8e8",
    "alpha": false
  },
  "ww-records": {
    "w": 1179,
    "h": 2077,
    "widths": [
      640,
      1179
    ],
    "color": "#787878",
    "alpha": false
  },
  "ww-tank": {
    "w": 2500,
    "h": 3750,
    "widths": [
      640,
      1280,
      1920,
      2500
    ],
    "color": "#98a8a8",
    "alpha": false
  }
} as const;

export type MediaName = keyof typeof mediaManifest;
