// Builds optimised, responsive media from /media-src into /public/media and
// writes a typed manifest to src/lib/media.generated.ts.
//
//   npm run media          (images + covers + videos)
//   npm run media -- --images-only
//
// Images → /public/media/img/<name>/<width>.webp
// Covers → /public/media/covers/<spotify-hash>-{300,640}.webp (self-hosted artwork)
// Videos → /public/media/video/<name>-{1080,720,preview}.mp4 + poster
import { readdir, mkdir, writeFile, stat, readFile, rm } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join, parse, dirname } from "node:path";
import { spawnSync } from "node:child_process";
import sharp from "sharp";

const ROOT = process.cwd();
const SRC_IMG = join(ROOT, "media-src/images");
const SRC_VID = join(ROOT, "media-src/video");
const OUT_IMG = join(ROOT, "public/media/img");
const OUT_COVERS = join(ROOT, "public/media/covers");
const OUT_VID = join(ROOT, "public/media/video");
const MANIFEST = join(ROOT, "src/lib/media.generated.ts");

const WIDTHS = [640, 1280, 1920, 2560];
const imagesOnly = process.argv.includes("--images-only");

const toHex = ({ r, g, b }) =>
  "#" + [r, g, b].map((v) => Math.round(v).toString(16).padStart(2, "0")).join("");

async function buildImages() {
  const files = (await readdir(SRC_IMG)).filter((f) => /\.(webp|jpe?g|png)$/i.test(f)).sort();
  const manifest = {};

  for (const file of files) {
    const name = parse(file).name;
    const input = join(SRC_IMG, file);
    const outDir = join(OUT_IMG, name);
    await mkdir(outDir, { recursive: true });

    const meta = await sharp(input, { failOn: "none" }).metadata();
    const isLogo = /^(logo|badge|award|whitewall-logo)/.test(name);
    const w0 = meta.width ?? 0;
    const h0 = meta.height ?? 0;

    const widths = WIDTHS.filter((w) => w < w0);
    widths.push(Math.min(w0, 2560));
    const unique = [...new Set(widths)].sort((a, b) => a - b);

    for (const w of unique) {
      const dest = join(outDir, `${w}.webp`);
      if (existsSync(dest)) continue;
      await sharp(input, { failOn: "none" })
        .resize({ width: w, withoutEnlargement: true })
        .webp({ quality: isLogo ? 90 : 78, effort: 5, alphaQuality: 100 })
        .toFile(dest);
    }

    // retired: pixel-step placeholders from the first build
    for (const p of [12, 24, 48]) {
      const old = join(outDir, `p${p}.webp`);
      if (existsSync(old)) await rm(old);
    }

    const { dominant } = await sharp(input, { failOn: "none" }).stats();
    manifest[name] = { w: w0, h: h0, widths: unique, color: toHex(dominant), alpha: !!meta.hasAlpha };
    process.stdout.write(`  img  ${name.padEnd(26)} ${w0}x${h0}  [${unique.join(", ")}]\n`);
  }

  const body =
    "// AUTO-GENERATED by scripts/build-media.mjs — do not edit by hand.\n" +
    "export const mediaManifest = " +
    JSON.stringify(manifest, null, 2) +
    " as const;\n\nexport type MediaName = keyof typeof mediaManifest;\n";
  await mkdir(dirname(MANIFEST), { recursive: true });
  await writeFile(MANIFEST, body);
  console.log(`\n  manifest → ${MANIFEST} (${files.length} images)`);
}

// Release artwork is pulled once from Spotify's CDN and served from our own
// origin, so covers never depend on a third-party host (or a browser's
// tracking protection) to appear.
async function buildCovers() {
  const src = await readFile(join(ROOT, "src/lib/content/tracks.ts"), "utf8");
  const hashes = [...new Set([...src.matchAll(/cover: "([0-9a-f]{24})"/g)].map((m) => m[1]))];
  await mkdir(OUT_COVERS, { recursive: true });
  let fetched = 0;
  for (const hash of hashes) {
    const d640 = join(OUT_COVERS, `${hash}-640.webp`);
    const d300 = join(OUT_COVERS, `${hash}-300.webp`);
    if (existsSync(d640) && existsSync(d300)) continue;
    const res = await fetch(`https://i.scdn.co/image/ab67616d0000b273${hash}`);
    if (!res.ok) {
      console.warn(`  cover ${hash} → HTTP ${res.status}`);
      continue;
    }
    const buf = Buffer.from(await res.arrayBuffer());
    await sharp(buf).resize(640, 640, { fit: "cover" }).webp({ quality: 80 }).toFile(d640);
    await sharp(buf).resize(300, 300, { fit: "cover" }).webp({ quality: 78 }).toFile(d300);
    fetched++;
  }
  console.log(`  covers → ${hashes.length} total, ${fetched} fetched`);
}

function ffmpeg(args) {
  const r = spawnSync("ffmpeg", ["-v", "error", "-y", ...args], { stdio: "inherit" });
  if (r.status !== 0) throw new Error("ffmpeg failed: " + args.join(" "));
}

// name → { trim (seconds), poster time, preview start }
const VIDEOS = {
  "reel-music": { trim: 31.8, poster: 4.6, preview: 3.2 },
  "reel-commercial": { trim: 30.8, poster: 2.4, preview: 1.4 },
};

async function buildVideos() {
  await mkdir(OUT_VID, { recursive: true });
  for (const [name, cfg] of Object.entries(VIDEOS)) {
    const input = join(SRC_VID, `${name}.mp4`);
    if (!existsSync(input)) continue;
    const video = ["-c:v", "libx264", "-pix_fmt", "yuv420p", "-movflags", "+faststart", "-preset", "slow"];
    // Full reels keep their audio (sound-on toggle); previews are silent loops.
    const audio = ["-c:a", "aac", "-b:a", "128k", "-ac", "2", "-af", "afade=t=out:st=" + (cfg.trim - 1.2) + ":d=1.2"];
    const out1080 = join(OUT_VID, `${name}-1080.mp4`);
    const out720 = join(OUT_VID, `${name}-720.mp4`);
    const outPrev = join(OUT_VID, `${name}-preview.mp4`);
    const poster = join(OUT_VID, `${name}-poster.webp`);
    if (!existsSync(out1080)) ffmpeg(["-i", input, "-t", String(cfg.trim), ...video, ...audio, "-crf", "27", "-vf", "scale=1920:-2", out1080]);
    if (!existsSync(out720)) ffmpeg(["-i", input, "-t", String(cfg.trim), ...video, ...audio, "-crf", "28", "-vf", "scale=1280:-2", out720]);
    if (!existsSync(outPrev)) ffmpeg(["-ss", String(cfg.preview), "-i", input, "-t", "7", "-an", ...video, "-crf", "30", "-vf", "scale=640:-2", outPrev]);
    if (!existsSync(poster)) ffmpeg(["-ss", String(cfg.poster), "-i", input, "-frames:v", "1", "-vf", "scale=1920:-2", "-c:v", "libwebp", "-quality", "80", poster]);
    for (const f of [out1080, out720, outPrev, poster]) {
      const s = await stat(f);
      console.log(`  vid  ${parse(f).base.padEnd(34)} ${(s.size / 1024 / 1024).toFixed(2)} MB`);
    }
  }
}

console.log("Building media…");
await buildImages();
await buildCovers();
if (!imagesOnly) await buildVideos();
console.log("Done.");
